### ISSUE TITLE
PUT request fails with 500 error.

### ISSUE THREAD

**Issue by Virnkord** [Aidbox/stresty#1]
<b> Request: </b>
```
PUT: /List/list-3
body:
- id: list-3
  resourceType: List
  status: "Generated"
  mode: "changes"
  subject: 
    resourceType: "Patient"
    id: "pt-2"
  entry:
  - item:
    resourceType: "Patient"
    id: "pt-1"
  - item:
    resourceType: "Patient"
    id: "pt-3"
match:
  status: 200
```
<b> Fails with error: </b>
```
status:  500 != 200
body:  
  resourceType:  OperationOutcome
  id:  exception
  text:  
    status:  generated
    div:  class clojure.lang.LazySeq cannot be cast to class clojure.lang.Associative (clojure.lang.LazySeq and clojure.lang.Associative are in unnamed module of loader 'app')
  issue:  
  - severity:  fatal
    code:  exception
    diagnostics:  class clojure.lang.LazySeq cannot be cast to class clojure.lang.Associative (clojure.lang.LazySeq and clojure.lang.Associative are in unnamed module of loader 'app')
```
